# see https://github.com/docker-library/postgres/issues/537#issuecomment-629886574

version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-super}
      # PGDATA: /data/postgres
    # volumes:
    #   - postgres:/data/postgres
    volumes:
      # - ./.local/pg/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - .local/pg/data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    # - ./backups:/backups
    # command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - postgres

  redis:
      image: redis
      container_name: super_redis
      restart: unless_stopped
      command: redis-server --appendonly yes
      ports:
        - ${REDIS_PORT:-6379}:6379
      volumes:
        - .local/redis/data:/data
      restart: always
      networks:
        - redis

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge

volumes:
  postgres:
  redis:
